dist: bionic

services:
  - docker

branches:
  only:
    - master
    - stable

env:
  DOCKER_COMPOSE_VERSION: 1.25.0

language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'

matrix:
  fast_finish: true

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - travis_retry composer update -n
  - docker build --pull --force-rm --no-cache -f ./Dockerfile-nginx -t mferly/mferly_nginx:latest .
  - docker build --pull --force-rm --no-cache -f ./Dockerfile-php -t mferly/mferly_php:latest .
  - docker-compose up -d

script:
  - sh ./test.sh

after_script:
  - docker-compose down

after_success:
  # - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mferly/mferly_nginx:latest
  - docker push mferly/mferly_php:latest
  # - sh ./docker-push.sh

sudo: required