version: '3'

services:
    nginx:
        image: ${APP_NAME}_nginx:latest
        ports:
            - 443:443
            - 80:80
        depends_on:
            - php

        # Edit APP_NAME in .env
        volumes:
            # mount your project dir
            - ./:/var/www/${APP_NAME}

            # mount the Nginx .conf's that we need for dev
            - ./docker/nginx/conf/nginx.conf /etc/nginx/nginx.conf
            - ./docker/nginx/conf/${APP_NAME}.conf /etc/nginx/conf.d/${APP_NAME}.conf

            # You're going to need to setup the following if you want SSL
            # Everything commented out below if required for SSL
            # Check out mkcert in the README.md
            # I've included ./docker/nginx/certs/dhparam.pem

            # The paths per two lines below MUST match what you have
            #   in ./docker/nginx/conf/self-signed.conf
            #     I'm referring to..
            #       ssl_certificate /etc/ssl/certs/${APP_NAME}-cert.pem
            #       ssl_certificate /etc/ssl/private/${APP_NAME}-key.pem

            # - ./docker/nginx/certs/${APP_NAME}-cert.pem /etc/ssl/certs/${APP_NAME}-cert.pem
            # - ./docker/nginx/certs/${APP_NAME}-key.pem /etc/ssl/private/${APP_NAME}-key.pem

            # dhparam.pem is included in this package.
            # - ./docker/nginx/certs/dhparam.pem /etc/nginx/dhparam.pem

            # The following are also included but likely need some tweaking to suit your env
            # - ./docker/nginx/conf/self-signed.conf /etc/nginx/conf.d/self-signed.conf
            # - ./docker/nginx/conf/ssl-params.conf /etc/nginx/conf.d/ssl-params.conf

    php:
        image: ${APP_NAME}_php:latest
        environment:
            TIMEZONE: America/Toronto
            APP_ENV: dev
        expose:
            - 9000
        deploy:
            mode: replicated
            replicas: 5
            restart_policy:
                condition: on-failure
        volumes:
            # mount our project dir for dev
            - ./:/var/www/${APP_NAME}