version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        ports:
            - 8080:80
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        environment:
            TIMEZONE: America/Toronto
            APP_ENV: prod
        expose:
            - 9000
        deploy:
            mode: replicated
            replicas: 5
            restart_policy:
                condition: on-failure
        volumes:
            - ./:/var/www/xx-array