version: '3'

services:
    nginx:
        image: mferly/mferly_nginx:latest
        ports:
            - 443:443
            - 80:80
        depends_on:
            - php
        volumes:
            - ./:/var/www/mferly
            - ./docker/nginx/certs/mferly-cert.pem /etc/ssl/certs/mferly-cert.pem
            - ./docker/nginx/certs/mferly-key.pem /etc/ssl/private/mferly-key.pem
            - ./docker/nginx/certs/dhparam.pem /etc/nginx/dhparam.pem
            - ./docker/nginx/conf/nginx.conf /etc/nginx/nginx.conf
            - ./docker/nginx/conf/mferly.conf /etc/nginx/conf.d/mferly.conf
            - ./docker/nginx/conf/self-signed.conf /etc/nginx/conf.d/self-signed.conf
            - ./docker/nginx/conf/ssl-params.conf /etc/nginx/conf.d/ssl-params.conf

    php:
        image: mferly/mferly_php:latest
        environment:
            TIMEZONE: America/Toronto
            APP_ENV: dev
        expose:
            - 9000
        deploy:
            mode: replicated
            replicas: 5
            restart_policy:
                condition: on-failure
        volumes:
            - ./:/var/www/mferly