FROM nginx:latest

RUN apt-get update && apt-get upgrade -y \
        ca-certificates \
        netcat-openbsd \
    && apt-get autoremove -y

COPY ./docker/nginx/certs/mferly-cert.pem /etc/ssl/certs/mferly-cert.pem
COPY ./docker/nginx/certs/mferly-key.pem /etc/ssl/private/mferly-key.pem
COPY ./docker/nginx/certs/dhparam.pem /etc/nginx/dhparam.pem
COPY ./docker/nginx/conf/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/conf/mferly.conf /etc/nginx/conf.d/mferly.conf
COPY ./docker/nginx/conf/self-signed.conf /etc/nginx/conf.d/self-signed.conf
COPY ./docker/nginx/conf/ssl-params.conf /etc/nginx/conf.d/ssl-params.conf

RUN update-ca-certificates