FROM php:7.4.1-fpm

RUN apt-get update && apt-get install -y --no-install-recommends \
        libmcrypt-dev \
        zlib1g-dev \
        libicu-dev \
        libonig-dev \
        libzip-dev \
    && docker-php-ext-install \
        intl \
        opcache \
        pcntl \
        iconv \
        zip \
        bcmath \
        posix \
    && docker-php-ext-enable \
        intl \
        opcache \
        pcntl \
        iconv \
        zip \
        bcmath \
        posix \
    && apt-get autoremove -y \
    && usermod -u 1000 www-data

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && mv composer.phar /usr/local/bin/composer \
    && chmod +x /usr/local/bin/composer

COPY . /var/www/xx-array
ENV APP_ENV prod
RUN sh /var/www/xx-array/bin/build.sh