version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        ports:
            - 8080:443
        depends_on:
            - php
        links:
            - php
        volumes:
            - ./:/var/www/xx-array
        networks:
            - app-network

    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        environment:
            TIMEZONE: America/Toronto
            APP_ENV: dev
        expose:
            - 9000
        deploy:
            mode: replicated
            replicas: 5
            restart_policy:
                condition: on-failure
        volumes:
            - ./:/var/www/xx-array
        networks:
            - app-network

networks:
    app-network:
        driver: bridge