version: '3'

services:
    nginx:
        image: ${REPO}/${APP_NAME}_nginx:latest
        ports:
            - 443:443
            - 80:80
        depends_on:
            - php
        volumes:
            - app:${APP_PATH}

    php:
        image: ${REPO}/${APP_NAME}_php:latest
        environment:
            TIMEZONE: America/Toronto
            APP_ENV: prod
        expose:
            - 9000
        deploy:
            mode: replicated
            replicas: 5
            restart_policy:
                condition: on-failure
        volumes:
            - app:${APP_PATH}

volumes:
    app: